

target 'ZLFoundation' do
    
    use_frameworks!

pod 'SnapKit', '~> 3.2.0'

#pod 'GTFoundation', '0.4.2'

pod 'Reachability',  '~> 3.0.0'
pod 'AFNetworking', '~> 3.1.0'
pod 'Masonry', '~> 1.0.2'
pod 'FMDB', '~> 2.6.2'
pod 'FMDBx', '~> 0.7.0'
pod 'FMDB/SQLCipher'
pod 'SDWebImage', '~>3.8'
pod 'SVProgressHUD', '~> 1.1.3'
pod 'CocoaLumberjack', '~> 2.0.1'
pod 'XMLDictionary', '~> 1.4'
pod 'MJRefresh', '~> 3.1.12'
pod 'MBProgressHUD', '~> 1.0.0'
#pod 'Bugly', '~> 2.4.2'
pod 'UMengAnalytics-NO-IDFA', '~> 4.2.5'
pod 'DZNEmptyDataSet', '~> 1.8.1'
pod 'AMapNavi-NO-IDFA'

pod 'pop', '~> 1.0.9'

end

